# Generated by Django 5.2.4 on 2025-07-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alert_enabled', models.BooleanField(default=True)),
                ('sound_alert_enabled', models.BooleanField(default=True)),
                ('alert_email_address', models.EmailField(default='admin@safe-eye.com', help_text='The email address where all alert notifications will be sent.', max_length=254)),
                ('email_alert_template', models.TextField(default="URGENT: An '{incident_type}' was detected.\n\nLocation: {location}\nTime: {timestamp}\nConfidence: {confidence:.2f}%\n\nPlease review the incident immediately.", help_text='The template for email alerts. Use placeholders like {incident_type}, {location}, etc.')),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
