# Generated by Django 5.2.4 on 2025-07-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_remove_incident_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
